name = "ACEhamiltonians"
uuid = "0c0b7517-201b-4082-a776-cd952d974092"
version = "0.0.1"

[deps]
ACE = "3e8ccfd2-c8b0-11ea-32f1-f3a5990fd77a"
ACEatoms = "1e34e032-0b37-4839-a012-196b35408c3c"
ACEbase = "14bae519-eb20-449c-a949-9c58ed33163e"
ACEfit = "ad31a8ef-59f5-4a01-b543-a85c2f73e95c"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
NeighbourLists = "2fcf5ba9-9ed4-57cf-b73f-ff513e316b9c"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ACE = "= 0.12.22"
ACEbase = "= 0.2.2"
ArgParse = "1"
ArrayInterface = "2"
DistributedArrays = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
